language: java
jdk:
  - openjdk10
cache:
  directories:
    - "$HOME/.m2"
sudo: enabled
install: false
git:
  depth: false
before_script:
  - mvn versions:set -DnewVersion=${TRAVIS_BUILD_NUMBER}
script:
  - mvn clean test package
notifications:
  email:
    on_success: always
    on_failure: always